"""Add PartType for categorization

Revision ID: 3363c99c56a8
Revises: 2ce3c9b84b1d
Create Date: 2025-03-28 14:48:21.690967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3363c99c56a8'
down_revision = '2ce3c9b84b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PartType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('Part', schema=None) as batch_op:
        batch_op.add_column(sa.Column('part_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_Part_part_type_id', 'PartType', ['part_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Part', schema=None) as batch_op:
        batch_op.drop_constraint('fk_Part_part_type_id', type_='foreignkey')
        batch_op.drop_column('part_type_id')

    op.drop_table('PartType')
    # ### end Alembic commands ###
